version: "3.3"

services:
  db:
    image: postgres:14.2
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: interview_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d interview-tracker"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7
    command: ["redis-server","--appendonly","yes"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  interview-tracker-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: interview-tracker-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./:/app        # mount โค้ดจาก host เข้า container
    depends_on:
      - db
      - redis
    restart: always

networks:
  default:
    driver: bridge

volumes:
  pgdata: {}
  redisdata: {}
