basePath: /
definitions:
  auth_models.LoginReq:
    properties:
      email:
        example: example@example.com
        type: string
      password:
        example: P@ssw0rd
        type: string
    required:
    - email
    - password
    type: object
  auth_models.RefreshReq:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  auth_models.TokenResponse:
    properties:
      access_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6Ikp..
        type: string
      ref_id:
        example: b2a8f4e5-9e3b-4c2b-9e0f-7b2c1a6d1f33
        type: string
      refresh_token:
        example: 0b83305f-75b2-4e89-a444-70da68f84d4f.0224f190-0f9a-46a4-a0fc-521fcc07e2ee..
        type: string
    type: object
  card_models.AddCommentReq:
    properties:
      content:
        example: ควรปรับปรุง portfolio ให้ละเอียดขึ้น
        type: string
    required:
    - content
    type: object
  card_models.CreateCardReq:
    properties:
      description:
        example: สัมภาษณ์ตำแหน่ง Backend Developer
        type: string
      scheduled_at:
        example: "2023-01-01T10:00:00Z"
        type: string
      title:
        example: นัดสัมภาษณ์งาน 1
        type: string
    required:
    - scheduled_at
    - title
    type: object
  card_models.UpdateCardReq:
    properties:
      description:
        example: สัมภาษณ์ตำแหน่ง Fullstack Developer
        type: string
      scheduled_at:
        example: "2023-01-02T15:00:00Z"
        type: string
      title:
        example: นัดสัมภาษณ์งาน 2
        type: string
    type: object
  card_models.UpdateCardStatusReq:
    properties:
      status:
        enum:
        - todo
        - in_progress
        - done
        example: in_progress
        type: string
    required:
    - status
    type: object
  card_models.UpdateCommentReq:
    properties:
      content:
        example: ใช้ได้
        type: string
    required:
    - content
    type: object
  entities.Role:
    properties:
      code:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      name:
        type: string
      updated_at:
        type: string
    type: object
  entities.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      name:
        type: string
      role:
        $ref: '#/definitions/entities.Role'
      role_id:
        type: string
      updated_at:
        type: string
    type: object
  user_models.CreateUserRequest:
    properties:
      email:
        example: example@example.com
        type: string
      is_active:
        type: boolean
      name:
        example: Soda Pop
        maxLength: 120
        type: string
      password:
        example: P@ssw0rd
        type: string
      role_id:
        example: a1bf3d66-e4ae-4d73-89c6-917f0f301003
        type: string
    required:
    - email
    - name
    - password
    - role_id
    type: object
  user_models.CreateUserResponse:
    properties:
      email:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      name:
        type: string
      role_id:
        type: string
    type: object
info:
  contact: {}
  description: API for Interview Tracker
  title: Interview Tracker API
  version: "1.0"
paths:
  /interview-tracker/authen/cards:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: page size
        in: query
        name: page_size
        type: integer
      - default: todo
        description: Filter status
        enum:
        - todo
        - in_progress
        - done
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: List cards
      tags:
      - cards
    post:
      consumes:
      - application/json
      parameters:
      - description: card create JSON
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/card_models.CreateCardReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Create card
      tags:
      - cards
  /interview-tracker/authen/cards/{id}:
    get:
      parameters:
      - description: card id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get card detail
      tags:
      - cards
    patch:
      consumes:
      - application/json
      parameters:
      - description: card id
        in: path
        name: id
        required: true
        type: string
      - description: patch
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/card_models.UpdateCardReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update card (partial)
      tags:
      - cards
  /interview-tracker/authen/cards/{id}/comments:
    get:
      parameters:
      - description: card id
        in: path
        name: id
        required: true
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: List comments
      tags:
      - comments
    post:
      consumes:
      - application/json
      parameters:
      - description: card id
        in: path
        name: id
        required: true
        type: string
      - description: comment
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/card_models.AddCommentReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Add comment
      tags:
      - comments
  /interview-tracker/authen/cards/{id}/history:
    get:
      parameters:
      - description: card id
        in: path
        name: id
        required: true
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: list history logs
      tags:
      - cards
  /interview-tracker/authen/cards/{id}/keep:
    post:
      consumes:
      - application/json
      parameters:
      - description: card id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: จัดเก็บ
      tags:
      - cards
  /interview-tracker/authen/cards/{id}/status:
    patch:
      consumes:
      - application/json
      parameters:
      - description: card id
        in: path
        name: id
        required: true
        type: string
      - description: new status
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/card_models.UpdateCardStatusReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Change status
      tags:
      - cards
  /interview-tracker/authen/cards/comments/{commentId}:
    patch:
      consumes:
      - application/json
      parameters:
      - description: commentId
        in: path
        name: commentId
        required: true
        type: string
      - description: patch
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/card_models.UpdateCommentReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update comment
      tags:
      - comments
  /interview-tracker/health:
    get:
      description: Returns success if the service is healthy
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: Health check
      tags:
      - health
  /interview-tracker/internal/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and issue access/refresh tokens (JWT access token
        has only sub/exp/iat/iss)
      parameters:
      - description: login JSON
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth_models.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/auth_models.TokenResponse'
      summary: Login
      tags:
      - auth
  /interview-tracker/internal/v1/auth/logout:
    post:
      description: Revoke current session using access token (refID is taken from
        JWT `sub`)
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: logout failed
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Logout
      tags:
      - auth
  /interview-tracker/internal/v1/auth/refresh:
    post:
      consumes:
      - application/json
      description: Rotate refresh token and issue a new access token
      parameters:
      - description: refresh JSON
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth_models.RefreshReq'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/auth_models.TokenResponse'
      summary: Refresh token
      tags:
      - auth
  /interview-tracker/internal/v1/users/create:
    post:
      consumes:
      - application/json
      description: Create user for
      parameters:
      - description: user create JSON
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user_models.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success response
          schema:
            $ref: '#/definitions/user_models.CreateUserResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create user
      tags:
      - users
  /interview-tracker/internal/v1/users/details/{userId}:
    get:
      consumes:
      - application/json
      description: Get user By ID
      parameters:
      - default: 888f2c6b-cc1a-4e94-bd6e-d8ba0ac36fc3
        description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/entities.User'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get user By ID
      tags:
      - users
  /interview-tracker/internal/v1/users/role-list:
    get:
      consumes:
      - application/json
      description: Get role
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            items:
              $ref: '#/definitions/entities.Role'
            type: array
        "500":
          description: Server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get role
      tags:
      - users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
